#!/usr/bin/env python3
import json
from pathlib import Path
SRC = Path(r"C:\Users\AMD\WorkBuddy\Kent Tools")
T = json.load(open(SRC / "_translations.json", encoding="utf-8"))

PATCH = {
"100% copper motor delivers 42KN crimping force": {
 "ar": "محرك نحاسي 100% يولد قوة ضغط 42KN",
 "de": "100 % Kupfermotor liefert 42KN Crimpkraft",
 "es": "Motor 100 % de cobre entrega 42KN de fuerza de engaste",
 "fr": "Moteur 100 % cuivre délivre 42KN de force de sertissage",
 "ja": "100%銅モーターが42KNの圧着力を発生",
 "pt": "Motor 100% cobre entrega 42KN de força de compressão",
 "ru": "100% медный мотор выдаёт усилие обжима 42KN"},
'4 US standard jaws: 1/2", 3/4", 1", 1-1/4" — covers 99% of common copper pipe jobs': {
 "ar": 'مقابس أمريكية قياسية 4: 1/2"، 3/4"، 1"، 1-1/4" — تغطي 99% من أعمال أنابيب النحاس الشائعة',
 "de": '4 US-Standard-Backen: 1/2", 3/4", 1", 1-1/4" — deckt 99 % der gängigen Kupferrohrarbeiten ab',
 "es": '4 mordazas estándar US: 1/2", 3/4", 1", 1-1/4" — cubre el 99 % de los trabajos comunes de tubos de cobre',
 "fr": '4 mâchoires standard US : 1/2", 3/4", 1", 1-1/4" — couvre 99 % des travaux courants sur cuivre',
 "ja": '米国標準ジョー4個: 1/2"、3/4"、1"、1-1/4" — 一般的な銅管作業の99%をカバー',
 "pt": '4 mandíbulas padrão US: 1/2", 3/4", 1", 1-1/4" — cobre 99% dos trabalhos comuns de tubos de cobre',
 "ru": '4 клещевых вкладыша стандарта US: 1/2", 3/4", 1", 1-1/4" — покрывают 99 % распространённых работ с медными трубами'},
"360° rotating jaw for complex and tight spaces": {
 "ar": "مفك برأس دوار 360° للأماكن المعقدة والضيقة",
 "de": "360° drehbare Backe für komplexe und enge Räume",
 "es": "Mordaza giratoria 360° para espacios complejos y estrechos",
 "fr": "Mâchoire rotative 360° pour les espaces complexes et étroits",
 "ja": "複雑で狭い場所向けの360°回転ジョー",
 "pt": "Mandíbula rotativa 360° para espaços complexos e estreitos",
 "ru": "Поворотная губка 360° для сложных и тесных мест"},
"Built-in LED light for low-light environments": {
 "ar": "إضاءة LED مدمجة للبيئات منخفضة الإضاءة",
 "de": "Eingebautes LED-Licht für schwach beleuchtete Umgebungen",
 "es": "Luz LED integrada para entornos con poca luz",
 "fr": "Lumière LED intégrée pour les environnements peu éclairés",
 "ja": "暗所向け内蔵LEDライト",
 "pt": "Luz LED integrada para ambientes com pouca luz",
 "ru": "Встроенная LED-подсветка для слабо освещённых мест"},
"Automatic pressure release after each crimp to protect the motor": {
 "ar": "إطلاق ضغط تلقائي بعد كل ضغط لحماية المحرك",
 "de": "Automatische Druckentlastung nach jedem Crimp zum Schutz des Motors",
 "es": "Liberación de presión automática tras cada engaste para proteger el motor",
 "fr": "Relâche de pression automatique après chaque sertissage pour protéger le moteur",
 "ja": "モーター保護のため各圧着後に自動圧力開放",
 "pt": "Liberação de pressão automática após cada crimpagem para proteger o motor",
 "ru": "Автоматический сброс давления после каждого обжима для защиты двигателя"},
"Temperature sensor and ventilation slots for heat dissipation": {
 "ar": "مستشعر حرارة وفتحات تهوية لتبديد الحرارة",
 "de": "Temperatursensor und Lüftungsschlitze zur Wärmeabfuhr",
 "es": "Sensor de temperatura y ranuras de ventilación para disipar el calor",
 "fr": "Capteur de température et fentes d'aération pour la dissipation de chaleur",
 "ja": "放熱のための温度センサーと換気スリット",
 "pt": "Sensor de temperatura e frestas de ventilação para dissipação de calor",
 "ru": "Датчик температуры и вентиляционные прорези для отвода тепла"},
"2 × 18V 5.0Ah lithium batteries — supports 400+ continuous crimps": {
 "ar": "بطاريتا ليثيوم 2 × 18V 5.0Ah — تدعم أكثر من 400 ضغطة متواصلة",
 "de": "2 × 18V 5,0Ah Lithium-Akkus — unterstützt 400+ fortlaufende Crimps",
 "es": "2 × baterías de litio 18V 5.0Ah — soporta 400+ engastes continuos",
 "fr": "2 × batteries lithium 18V 5,0Ah — prend en charge 400+ sertissages continus",
 "ja": "2×18V 5.0Ahリチウムバッテリー — 400回以上の連続圧着に対応",
 "pt": "2 × baterias de lítio 18V 5.0Ah — suporta 400+ crimps contínuos",
 "ru": "2 × литиевых аккумулятора 18V 5,0Ah — поддерживает 400+ непрерывных обжимов"},
"Universal charger included": {
 "ar": "شاحن عالمي مشمول", "de": "Universalladegerät enthalten", "es": "Cargador universal incluido",
 "fr": "Chargeur universel inclus", "ja": "ユニバーサル充電器付属", "pt": "Carregador universal incluído", "ru": "Универсальное зарядное устройство в комплекте"},
"100% copper brushless motor — max 60KN crimping force": {
 "ar": "محرك نحاسي 100% بدون فرشاة — قوة ضغط قصوى 60KN",
 "de": "100 % Kupfer-Bürstenloser Motor — max. 60KN Crimpkraft",
 "es": "Motor 100 % de cobre sin escobillas — fuerza máx. 60KN",
 "fr": "Moteur 100 % cuivre sans balais — force max. 60KN",
 "ja": "100%銅ブラシレスモーター — 最大60KN圧着力",
 "pt": "Motor 100% cobre sem escova — força máx. 60KN",
 "ru": "100% медный бессчёточный двигатель — макс. усилие обжима 60KN"},
'12 dies included: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (US standard)': {
 "ar": '12 قالباً مشمولة: 10، 16، 25، 35، 50، 70، 95، 120، 150، 185، 240، 300# (قياس أمريكي)',
 "de": '12 Matrizen enthalten: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (US-Standard)',
 "es": '12 dados incluidos: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (estándar US)',
 "fr": '12 matrices incluses : 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (standard US)',
 "ja": '12ダイス付属: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (米国標準)',
 "pt": '12 matrizes incluídas: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (padrão US)',
 "ru": '12 вкладышей в комплекте: 10, 16, 25, 35, 50, 70, 95, 120, 150, 185, 240, 300# (стандарт US)'},
"Crimping range: 8AWG to 600MCM": {
 "ar": "نطاق الضغط: من 8AWG إلى 600MCM", "de": "Crimpbereich: 8AWG bis 600MCM",
 "es": "Rango de engaste: 8AWG a 600MCM", "fr": "Plage de sertissage : 8AWG à 600MCM",
 "ja": "圧着範囲: 8AWG～600MCM", "pt": "Faixa de compressão: 8AWG a 600MCM",
 "ru": "Диапазон обжима: 8AWG до 600MCM"},
"OLED display — real-time power and usage counter": {
 "ar": "شاشة OLED — طاقة لحظية وعداد استخدام",
 "de": "OLED-Display — Echtzeit-Leistung und Nutzungszähler",
 "es": "Pantalla OLED — potencia en tiempo real y contador de uso",
 "fr": "Écran OLED — puissance en temps réel et compteur d'utilisation",
 "ja": "OLEDディスプレイ — リアルタイム電力と使用回数カウンター",
 "pt": "Display OLED — potência em tempo real e contador de uso",
 "ru": "OLED-дисплей — мощность в реальном времени и счётчик использования"},
"360° rotating jaw for flexible positioning": {
 "ar": "مفك دوار 360° للتوجيه المرن", "de": "360° drehbare Backe für flexible Positionierung",
 "es": "Mordaza giratoria 360° para posicionamiento flexible",
 "fr": "Mâchoire rotative 360° pour un positionnement flexible",
 "ja": "柔軟な位置決めのための360°回転ジョー",
 "pt": "Mandíbula rotativa 360° para posicionamento flexível",
 "ru": "Поворотная губка 360° для гибкого позиционирования"},
"LED work light for low-visibility conditions": {
 "ar": "مصباح عمل LED لظروف الرؤية المنخفضة",
 "de": "LED-Arbeitslicht für Bedingungen mit geringer Sicht",
 "es": "Luz de trabajo LED para condiciones de baja visibilidad",
 "fr": "Lumière de travail LED pour les conditions de faible visibilité",
 "ja": "視界不良時用LED作業ライト",
 "pt": "Luz de trabalho LED para condições de baixa visibilidade",
 "ru": "Рабочая LED-подсветка для условий слабой видимости"},
"Automatic pressure release and retraction after each crimp": {
 "ar": "إطلاق ضغط وانسحاب تلقائي بعد كل ضغط",
 "de": "Automatische Druckentlastung und Rückzug nach jedem Crimp",
 "es": "Liberación y retracción de presión automática tras cada engaste",
 "fr": "Relâche et rétraction de pression automatiques après chaque sertissage",
 "ja": "各圧着後の自動圧力開放と復帰",
 "pt": "Liberação e retração de pressão automáticas após cada crimpagem",
 "ru": "Автоматический сброс давления и возврат после каждого обжима"},
"Temperature sensor &amp; ventilation for heat dissipation": {
 "ar": "مستشعر حرارة وتروية لتبديد الحرارة",
 "de": "Temperatursensor &amp; Lüftung zur Wärmeabfuhr",
 "es": "Sensor de temperatura y ventilación para disipar el calor",
 "fr": "Capteur de température et ventilation pour la dissipation de chaleur",
 "ja": "放熱のための温度センサーと換気",
 "pt": "Sensor de temperatura e ventilação para dissipação de calor",
 "ru": "Датчик температуры и вентиляция для отвода тепла"},
"2 × 18V 5.0Ah batteries — approx. 300 crimps per charge": {
 "ar": "بطاريتان 2 × 18V 5.0Ah — حوالي 300 ضغطة لكل شحنة",
 "de": "2 × 18V 5,0Ah Akkus — ca. 300 Crimps pro Ladung",
 "es": "2 × baterías 18V 5.0Ah — aprox. 300 engastes por carga",
 "fr": "2 × batteries 18V 5,0Ah — environ 300 sertissages par charge",
 "ja": "2×18V 5.0Ahバッテリー — 満充電あたり約300回圧着",
 "pt": "2 × baterias 18V 5.0Ah — aprox. 300 crimps por carga",
 "ru": "2 × аккумулятора 18V 5,0Ah — ок. 300 обжимов на заряд"},
"Max 10TON crimping force — handles heavy-duty jobs with ease": {
 "ar": "قوة ضغط قصوى 10TON — تتعامل مع المهام الثقيلة بسهولة",
 "de": "Max. 10TON Crimpkraft — bewältigt Schwerstarbeiten mühelos",
 "es": "Fuerza máx. 10TON — maneja trabajos pesados con facilidad",
 "fr": "Force max. 10TON — gère les travaux lourds avec facilité",
 "ja": "最大10TON圧着力 — 重労働も楽にこなす",
 "pt": "Força máx. 10TON — lida com trabalhos pesados com facilidade",
 "ru": "Макс. усилие обжима 10TON — легко справляется с тяжёлыми задачами"},
"9 pairs of US standard dies — 12AWG to 2/0AWG": {
 "ar": "9 أزواج من القوالب القياسية الأمريكية — من 12AWG إلى 2/0AWG",
 "de": "9 Paare US-Standard-Matrizen — 12AWG bis 2/0AWG",
 "es": "9 pares de dados estándar US — 12AWG a 2/0AWG",
 "fr": "9 paires de matrices standard US — 12AWG à 2/0AWG",
 "ja": "9組の米国標準ダイス — 12AWG～2/0AWG",
 "pt": "9 pares de matrizes padrão US — 12AWG a 2/0AWG",
 "ru": "9 пар вкладышей стандарта US — 12AWG до 2/0AWG"},
"Upgraded hydraulic system with seal ring design — prevents oil leaks": {
 "ar": "نظام هيدروليكي مطور بتصميم حلقة seal — يمنع تسرب الزيت",
 "de": "Verbessertes Hydrauliksystem mit Dichtungsring-Design — verhindert Öllecks",
 "es": "Sistema hidráulico mejorado con diseño de anillo de sellado — evita fugas de aceite",
 "fr": "Système hydraulique amélioré avec anneau de joint — évite les fuites d'huile",
 "ja": "シールリング構造の改良油圧システム — オイル漏れを防止",
 "pt": "Sistema hidráulico melhorado com design de anel de vedação — evita vazamentos de óleo",
 "ru": "Улучшенная гидросистема с уплотнительным кольцом — предотвращает утечки масла"},
"Bayonet die mount — stable, quick die changes": {
 "ar": "تركيب قالب بيونيه — تغيير قوالب مستقر وسريع",
 "de": "Bajonett-Matrizenaufnahme — stabiler, schneller Matrizenwechsel",
 "es": "Montaje de matriz tipo bayoneta — cambios de dado estables y rápidos",
 "fr": "Monture de matrice baïonnette — changements de matrices stables et rapides",
 "ja": "バヨネットダイス取付 — 安定した素早いダイス交換",
 "pt": "Fixação de matriz tipo baioneta — trocas de matriz estáveis e rápidas",
 "ru": "Байонетное крепление вкладыша — стабильная, быстрая смена"},
"Quick-release return valve — fast piston reset between crimps": {
 "ar": "صمام عودة سريع الإطلاق — إعادة ضبط المكبس بسرعة بين الضغطات",
 "de": "Schnellentriegelungs-Rücklaufventil — schneller Kolbenrücksetzung zwischen Crimps",
 "es": "Válvula de retorno de liberación rápida — reinicio rápido del pistón entre engastes",
 "fr": "Vanne de retour à libération rapide — réinitialisation rapide du piston entre sertissages",
 "ja": "クイックリリースリターンバルブ — 圧着間のピストン復帰が早い",
 "pt": "Válvula de retorno de liberação rápida — reinício rápido do pistão entre crimpagens",
 "ru": "Клапан возврата с быстрой разблокировкой — быстрый возврат поршня между обжимами"},
"High-strength steel construction with rust-proof galvanized finish": {
 "ar": "هيكل فولاذي عالي المتانة بلمسة مجلفنة مقاومة للصدأ",
 "de": "Hochfester Stahlbau mit rostfreier verzinkter Oberfläche",
 "es": "Construcción de acero de alta resistencia con acabado galvanizado antirust",
 "fr": "Construction en acier haute résistance avec finition galvanisée antirouille",
 "ja": "高強度スチール製、錆びにくい亜鉛メッキ仕上げ",
 "pt": "Construção em aço de alta resistência com acabamento galvanizado à prova de ferrugem",
 "ru": "Конструкция из высокопрочной стали с антикоррозийным оцинкованным покрытием"},
"5 replaceable seal rings included for extended service life": {
 "ar": "5 حلقات seal قابلة للاستبدال مشمولة لعمر خدمة أطول",
 "de": "5 auswechselbare Dichtungsringe für längere Lebensdauer enthalten",
 "es": "5 anillos de sellado reemplazables incluidos para mayor vida útil",
 "fr": "5 anneaux de joint remplaçables inclus pour une durée de vie prolongée",
 "ja": "長寿命のための交換可能なシールリング5個付属",
 "pt": "5 anéis de vedação substituíveis incluídos para maior vida útil",
 "ru": "5 сменных уплотнительных колец в комплекте для продления срока службы"},
"Compact and portable — no battery or power source needed": {
 "ar": "مضغوط ومحمول — لا يحتاج بطارية أو مصدر طاقة",
 "de": "Kompakt und tragbar — keine Batterie oder Stromquelle nötig",
 "es": "Compacto y portátil — no necesita batería ni fuente de alimentación",
 "fr": "Compact et portable — aucune batterie ni source d'alimentation requise",
 "ja": "コンパクトで携帯性高 — バッテリーや電源不要",
 "pt": "Compacto e portátil — não precisa de bateria ou fonte de energia",
 "ru": "Компактный и переносной — не нужны батарея или источник питания"},
"Ultra-lightweight — only 5.7 lbs net (9.7 lbs with jaws+battery)": {
 "ar": "خفيف جداً — 5.7 رطل صافٍ فقط (9.7 رطل مع الفك والبطارية)",
 "de": "Ultraleicht — nur 5,7 lbs netto (9,7 lbs mit Backen+Akku)",
 "es": "Ultra ligero — solo 5,7 lbs neto (9,7 lbs con mordazas+batería)",
 "fr": "Ultra léger — seulement 5,7 lbs net (9,7 lbs avec mâchoires+batterie)",
 "ja": "超軽量 — 本体わずか5.7 lbs（ジョー＋バッテリーで9.7 lbs）",
 "pt": "Ultra leve — apenas 5,7 lbs líquido (9,7 lbs com mandíbulas+bateria)",
 "ru": "Сверхлёгкий — всего 5,7 фунта нетто (9,7 фунта с губками+аккумулятором)"},
"Upright single-hand design for narrow passages and complex jobs": {
 "ar": "تصميم عمودي بيد واحدة للممرات الضيقة والوظائف المعقدة",
 "de": "Aufrechtes Einhand-Design für enge Durchgänge und komplexe Arbeiten",
 "es": "Diseño vertical de una mano para pasajes estrechos y trabajos complejos",
 "fr": "Conception verticale à une main pour les passages étroits et les travaux complexes",
 "ja": "狭い場所や複雑な作業向けの直立片手設計",
 "pt": "Design vertical de uma mão para passagens estreitas e trabalhos complexos",
 "ru": "Вертикальная одноручная конструкция для узких проходов и сложных задач"},
"100% copper motor delivers 32KN crimping force": {
 "ar": "محرك نحاسي 100% يولد قوة ضغط 32KN",
 "de": "100 % Kupfermotor liefert 32KN Crimpkraft",
 "es": "Motor 100 % de cobre entrega 32KN de fuerza de engaste",
 "fr": "Moteur 100 % cuivre délivre 32KN de force de sertissage",
 "ja": "100%銅モーターが32KNの圧着力を発生",
 "pt": "Motor 100% cobre entrega 32KN de força de compressão",
 "ru": "100% медный мотор выдаёт усилие обжима 32KN"},
'3 US standard jaws: 1/2", 3/4", 1" — compatible with Viega and MegaPress': {
 "ar": '3 فكوك أمريكية قياسية: 1/2"، 3/4"، 1" — متوافقة مع Viega وMegaPress',
 "de": '3 US-Standard-Backen: 1/2", 3/4", 1" — kompatibel mit Viega und MegaPress',
 "es": '3 mordazas estándar US: 1/2", 3/4", 1" — compatibles con Viega y MegaPress',
 "fr": '3 mâchoires standard US : 1/2", 3/4", 1" — compatibles avec Viega et MegaPress',
 "ja": '米国標準ジョー3個: 1/2"、3/4"、1" — ViegaとMegaPress対応',
 "pt": '3 mandíbulas padrão US: 1/2", 3/4", 1" — compatíveis com Viega e MegaPress',
 "ru": '3 клещевых вкладыша стандарта US: 1/2", 3/4", 1" — совместимо с Viega и MegaPress'},
"OLED display for real-time power and usage monitoring": {
 "ar": "شاشة OLED للمراقبة اللحظية للطاقة والاستخدام",
 "de": "OLED-Display zur Echtzeit-Überwachung von Leistung und Nutzung",
 "es": "Pantalla OLED para monitoreo de potencia y uso en tiempo real",
 "fr": "Écran OLED pour le suivi en temps réel de la puissance et de l'utilisation",
 "ja": "リアルタイム電力・使用監視用OLEDディスプレイ",
 "pt": "Display OLED para monitoramento de potência e uso em tempo real",
 "ru": "OLED-дисплей для мониторинга мощности и использования в реальном времени"},
"360° swiveling jaws for flexible positioning": {
 "ar": "فكوك دوارة 360° للتوجيه المرن",
 "de": "360° schwenkbare Backen für flexible Positionierung",
 "es": "Mordazas giratorias 360° para posicionamiento flexible",
 "fr": "Mâchoires pivotantes 360° pour un positionnement flexible",
 "ja": "柔軟な位置決めのための360°首振りジョー",
 "pt": "Mandíbulas giratórias 360° para posicionamento flexível",
 "ru": "Поворотные губки 360° для гибкого позиционирования"},
"2 × 18V 2.5Ah lithium batteries — fully rechargeable within 1 hour": {
 "ar": "بطاريتا ليثيوم 2 × 18V 2.5Ah — قابلتان لإعادة الشحن الكامل خلال ساعة",
 "de": "2 × 18V 2,5Ah Lithium-Akkus — voll aufladbar innerhalb 1 Stunde",
 "es": "2 × baterías de litio 18V 2.5Ah — recargables totalmente en 1 hora",
 "fr": "2 × batteries lithium 18V 2,5Ah — rechargeables complètement en 1 heure",
 "ja": "2×18V 2.5Ahリチウムバッテリー — 1時間以内でフル充電",
 "pt": "2 × baterias de lítio 18V 2.5Ah — recarregáveis por completo em 1 hora",
 "ru": "2 × литиевых аккумулятора 18V 2,5Ah — полная зарядка менее чем за 1 час"},
"Includes shoulder straps for easy carrying on site": {
 "ar": "تشمل أحزمة كتف للحمل السهل في الموقع",
 "de": "Enthält Tragegurte für einfaches Tragen auf der Baustelle",
 "es": "Incluye correas de hombro para fácil transporte en obra",
 "fr": "Inclut des bretelles pour un transport facile sur site",
 "ja": "現場での楽な運搬用ショルダーストラップ付属",
 "pt": "Inclui alças de ombro para transporte fácil no local",
 "ru": "Включает плечевые ремни для удобной переноски на объекте"},
"120KN (12 TON) crimping force — highest in class": {
 "ar": "قوة ضغط 120KN (12 TON) — الأعلى في فئتها",
 "de": "120KN (12 TON) Crimpkraft — höchste in der Klasse",
 "es": "Fuerza de engaste 120KN (12 TON) — la más alta de su clase",
 "fr": "Force de sertissage 120KN (12 TON) — la plus élevée de sa catégorie",
 "ja": "120KN（12TON）圧着力 — クラス最高",
 "pt": "Força de compressão 120KN (12 TON) — a mais alta da categoria",
 "ru": "Усилие обжима 120KN (12 TON) — самое высокое в классе"},
"100% copper brushless motor — completes crimps in 5-8 seconds": {
 "ar": "محرك نحاسي 100% بدون فرشاة — يكمل الضغط في 5-8 ثوانٍ",
 "de": "100 % Kupfer-Bürstenloser Motor — Crimps in 5-8 Sekunden",
 "es": "Motor 100 % de cobre sin escobillas — completa engastes en 5-8 segundos",
 "fr": "Moteur 100 % cuivre sans balais — complète les sertissages en 5-8 secondes",
 "ja": "100%銅ブラシレスモーター — 5〜8秒で圧着完了",
 "pt": "Motor 100% cobre sem escova — completa crimps em 5-8 segundos",
 "ru": "100% медный бессчёточный двигатель — завершает обжим за 5-8 секунд"},
'12 dies included: 16#-400# (6AWG to 800MCM) — US standard': {
 "ar": '12 قالباً مشمولة: 16#-400# (6AWG إلى 800MCM) — قياس أمريكي',
 "de": '12 Matrizen enthalten: 16#-400# (6AWG bis 800MCM) — US-Standard',
 "es": '12 dados incluidos: 16#-400# (6AWG a 800MCM) — estándar US',
 "fr": '12 matrices incluses : 16#-400# (6AWG à 800MCM) — standard US',
 "ja": '12ダイス付属: 16#-400# (6AWG～800MCM) — 米国標準',
 "pt": '12 matrizes incluídas: 16#-400# (6AWG a 800MCM) — padrão US',
 "ru": '12 вкладышей в комплекте: 16#-400# (6AWG до 800MCM) — стандарт US'},
"18V 5.0Ah battery × 2 — approx. 300 crimps per full charge": {
 "ar": "بطارية 18V 5.0Ah × 2 — حوالي 300 ضغطة لكل شحنة كاملة",
 "de": "18V 5,0Ah Akku × 2 — ca. 300 Crimps pro voller Ladung",
 "es": "Batería 18V 5.0Ah × 2 — aprox. 300 engastes por carga completa",
 "fr": "Batterie 18V 5,0Ah × 2 — environ 300 sertissages par charge complète",
 "ja": "18V 5.0Ahバッテリー×2 — 満充電あたり約300回圧着",
 "pt": "Bateria 18V 5.0Ah × 2 — aprox. 300 crimps por carga completa",
 "ru": "Аккумулятор 18V 5,0Ah × 2 — ок. 300 обжимов на полную зарядку"},
"360° swiveling jaw for flexible positioning in tight spaces": {
 "ar": "فك دوار 360° للتوجيه المرن في الأماكن الضيقة",
 "de": "360° schwenkbare Backe für flexible Positionierung in engen Räumen",
 "es": "Mordaza giratoria 360° para posicionamiento flexible en espacios estrechos",
 "fr": "Mâchoire pivotante 360° pour un positionnement flexible dans les espaces étroits",
 "ja": "狭い場所での柔軟な位置決めのための360°首振りジョー",
 "pt": "Mandíbula giratória 360° para posicionamento flexível em espaços estreitos",
 "ru": "Поворотная губка 360° для гибкого позиционирования в тесных местах"},
"Built-in LED work light for low-light environments": {
 "ar": "مصباح عمل LED مدمج لبيئات منخفضة الإضاءة",
 "de": "Eingebautes LED-Arbeitslicht für schwach beleuchtete Umgebungen",
 "es": "Luz de trabajo LED integrada para entornos con poca luz",
 "fr": "Lumière de travail LED intégrée pour les environnements peu éclairés",
 "ja": "暗所向け内蔵LED作業ライト",
 "pt": "Luz de trabalho LED integrada para ambientes com pouca luz",
 "ru": "Встроенная рабочая LED-подсветка для слабо освещённых мест"},
'6 US standard jaws: 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — covers 99% of jobs': {
 "ar": '6 فكوك أمريكية قياسية: 1/2"، 3/4"، 1"، 1-1/4"، 1-1/2"، 2" — تغطي 99% من الأعمال',
 "de": '6 US-Standard-Backen: 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — deckt 99 % der Arbeiten ab',
 "es": '6 mordazas estándar US: 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — cubre el 99 % de los trabajos',
 "fr": '6 mâchoires standard US : 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — couvre 99 % des travaux',
 "ja": '米国標準ジョー6個: 1/2"、3/4"、1"、1-1/4"、1-1/2"、2" — 作業の99%をカバー',
 "pt": '6 mandíbulas padrão US: 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — cobre 99% dos trabalhos',
 "ru": '6 клещевых вкладышей стандарта US: 1/2", 3/4", 1", 1-1/4", 1-1/2", 2" — покрывают 99 % работ'},
"18V 5.0Ah battery × 2 — supports 400+ continuous crimps per charge": {
 "ar": "بطارية 18V 5.0Ah × 2 — تدعم أكثر من 400 ضغطة متواصلة لكل شحنة",
 "de": "18V 5,0Ah Akku × 2 — unterstützt 400+ fortlaufende Crimps pro Ladung",
 "es": "Batería 18V 5.0Ah × 2 — soporta 400+ engastes continuos por carga",
 "fr": "Batterie 18V 5,0Ah × 2 — prend en charge 400+ sertissages continus par charge",
 "ja": "18V 5.0Ahバッテリー×2 — 満充電あたり400回以上の連続圧着に対応",
 "pt": "Bateria 18V 5.0Ah × 2 — suporta 400+ crimps contínuos por carga",
 "ru": "Аккумулятор 18V 5,0Ah × 2 — поддерживает 400+ непрерывных обжимов на заряд"},
"200% more runtime than 2.0Ah batteries": {
 "ar": "مدة تشغيل أطول بنسبة 200% مقارنة ببطاريات 2.0Ah",
 "de": "200 % längere Laufzeit als 2,0Ah Akkus",
 "es": "200 % más autonomía que las baterías de 2.0Ah",
 "fr": "200 % d'autonomie en plus que les batteries 2,0Ah",
 "ja": "2.0Ahバッテリーより200%長い連続使用時間",
 "pt": "200% mais tempo de uso que baterias de 2.0Ah",
 "ru": "На 200 % больше времени работы, чем у аккумуляторов 2,0Ah"},
"Fast 3-6 seconds press cycle with automatic pressure release": {
 "ar": "دورة ضغط سريعة 3-6 ثوانٍ مع إطلاق ضغط تلقائي",
 "de": "Schneller 3-6 Sekunden Presszyklus mit automatischer Druckentlastung",
 "es": "Ciclo de prensado rápido de 3-6 segundos con liberación de presión automática",
 "fr": "Cycle de presse rapide 3-6 secondes avec relâche de pression automatique",
 "ja": "自動圧力開放付きの素早い3〜6秒プレスサイクル",
 "pt": "Ciclo de prensagem rápido de 3-6 segundos com liberação de pressão automática",
 "ru": "Быстрый цикл прессования 3-6 секунд с автоматическим сбросом давления"},
"350° swiveling jaw adapts to complex environments": {
 "ar": "فك دوار 350° يتكيف مع البيئات المعقدة",
 "de": "350° schwenkbare Backe passt sich komplexen Umgebungen an",
 "es": "Mordaza giratoria 350° se adapta a entornos complejos",
 "fr": "Mâchoire pivotante 350° s'adapte aux environnements complexes",
 "ja": "複雑な環境に適応する350°首振りジョー",
 "pt": "Mandíbula giratória 350° adapta-se a ambientes complexos",
 "ru": "Поворотная губка 350° адаптируется к сложным условиям"},
"Built-in LED work light for low-light conditions": {
 "ar": "مصباح عمل LED مدمج لظروف إضاءة منخفضة",
 "de": "Eingebautes LED-Arbeitslicht für Bedingungen mit wenig Licht",
 "es": "Luz de trabajo LED integrada para condiciones de poca luz",
 "fr": "Lumière de travail LED intégrée pour les conditions de faible éclairage",
 "ja": "低照度条件下用内蔵LED作業ライト",
 "pt": "Luz de trabalho LED integrada para condições de pouca luz",
 "ru": "Встроенная рабочая LED-подсветка для условий слабого освещения"},
"Dual brushless motor — 0.7 seconds tying speed": {
 "ar": "محرك مزدوج بدون فرشاة — سرعة ربط 0.7 ثانية",
 "de": "Doppelter bürstenloser Motor — 0,7 Sekunden Bindungsgeschwindigkeit",
 "es": "Motor doble sin escobillas — velocidad de amarre 0,7 segundos",
 "fr": "Double moteur sans balais — vitesse de ligature 0,7 seconde",
 "ja": "デュアルブラシレスモーター — 結束速度0.7秒",
 "pt": "Motor duplo sem escova — velocidade de amarração 0,7 segundo",
 "ru": "Двойной бессчёточный двигатель — скорость вязки 0,7 секунды"},
"Tie with dual 1.0mm wire, keeps rebar from loosening": {
 "ar": "ربط بسلك مزدوج 1.0mm، يمنع ارتخاء حديد التسليح",
 "de": "Binden mit doppeltem 1,0mm Draht, verhindert das Lösen der Bewehrung",
 "es": "Amarre con alambre doble de 1,0mm, evita que la armadura se afloje",
 "fr": "Ligature avec fil double 1,0mm, empêche la barre d'armature de se desserrer",
 "ja": "1.0mm二重ワイヤーで結束、鉄筋の緩みを防止",
 "pt": "Amarre com fio duplo de 1,0mm, evita o afrouxamento da armadura",
 "ru": "Вязка двойной проволокой 1,0mm, предотвращает ослабление арматуры"},
"1-5 levels adjustable tension with digital control &amp; warning sensor": {
 "ar": "شد قابل للضبط بمستويات 1-5 مع تحكم رقمي ومستشعر تحذير",
 "de": "1-5 Stufen einstellbare Spannung mit digitaler Steuerung &amp; Warnsensor",
 "es": "Tensión ajustable de 1-5 niveles con control digital y sensor de advertencia",
 "fr": "Tension réglable de 1 à 5 niveaux avec contrôle numérique et capteur d'alerte",
 "ja": "1〜5段階調整テンション、デジタル制御と警告センサー付き",
 "pt": "Tensão ajustável de 1-5 níveis com controle digital e sensor de aviso",
 "ru": "Регулируемое натяжение 1-5 уровней с цифровым управлением и датчиком предупреждения"},
"Over 4,000 ties per charge (18V 5.0Ah Li-ion battery)": {
 "ar": "أكثر من 4,000 ربطة لكل شحنة (بطارية ليثيوم أيون 18V 5.0Ah)",
 "de": "Über 4.000 Bindungen pro Ladung (18V 5,0Ah Li-Ion-Akku)",
 "es": "Más de 4.000 amarres por carga (batería de iones de litio 18V 5.0Ah)",
 "fr": "Plus de 4 000 ligatures par charge (batterie lithium-ion 18V 5,0Ah)",
 "ja": "満充電あたり4,000回以上の結束（18V 5.0Ahリチウムイオンバッテリー）",
 "pt": "Mais de 4.000 amarres por carga (bateria de lítio-ión 18V 5.0Ah)",
 "ru": "Более 4 000 вязок на заряд (литиево-ионный аккумулятор 18V 5,0Ah)"},
"Ergonomic lightweight design — reduces physical strain": {
 "ar": "تصميم خفيف مريح — يقلل الإجهاد البدني",
 "de": "Ergonomisches leichtes Design — reduziert körperliche Belastung",
 "es": "Diseño ergonómico y ligero — reduce la fatiga física",
 "fr": "Conception ergonomique et légère — réduit la fatigue physique",
 "ja": "人間工学に基づいた軽量設計 — 身体的負担を軽減",
 "pt": "Design ergonômico e leve — reduz o esforço físico",
 "ru": "Эргономичный лёгкий дизайн — снижает физическую нагрузку"},
"Single-hand operation — 0.7-0.8 seconds tying speed": {
 "ar": "تشغيل بيد واحدة — سرعة ربط 0.7-0.8 ثانية",
 "de": "Einhandbedienung — 0,7-0,8 Sekunden Bindungsgeschwindigkeit",
 "es": "Operación con una mano — velocidad de amarre 0,7-0,8 segundos",
 "fr": "Fonctionnement à une main — vitesse de ligature 0,7-0,8 seconde",
 "ja": "片手操作 — 結束速度0.7〜0.8秒",
 "pt": "Operação com uma mão — velocidade de amarração 0,7-0,8 segundo",
 "ru": "Одноручная работа — скорость вязки 0,7-0,8 секунды"},
"1-10 levels adjustable tension with digital control": {
 "ar": "شد قابل للضبط بمستويات 1-10 مع تحكم رقمي",
 "de": "1-10 Stufen einstellbare Spannung mit digitaler Steuerung",
 "es": "Tensión ajustable de 1-10 niveles con control digital",
 "fr": "Tension réglable de 1 à 10 niveaux avec contrôle numérique",
 "ja": "1〜10段階調整テンション、デジタル制御",
 "pt": "Tensão ajustável de 1-10 níveis com controle digital",
 "ru": "Регулируемое натяжение 1-10 уровней с цифровым управлением"},
"Single brushless motor — extended operational life": {
 "ar": "محرك أحادي بدون فرشاة — عمر تشغيلي أطول",
 "de": "Einzelner bürstenloser Motor — verlängerte Betriebslebensdauer",
 "es": "Motor único sin escobillas — vida útil prolongada",
 "fr": "Moteur unique sans balais — durée de vie opérationnelle prolongée",
 "ja": "シングルブラシレスモーター — 長い稼働寿命",
 "pt": "Motor único sem escova — vida útil estendida",
 "ru": "Один бессчёточный двигатель — продлённый срок службы"},
"2 or 3 wrap options for secure fastening": {
 "ar": "خيارا تغليف 2 أو 3 لربط آمن",
 "de": "2 oder 3 Wickeloptionen für sicheren Halt",
 "es": "Opciones de 2 o 3 vueltas para sujeción segura",
 "fr": "Options de 2 ou 3 tours pour une fixation sécurisée",
 "ja": "確実な固定のための2または3巻きオプション",
 "pt": "Opções de 2 ou 3 voltas para fixação segura",
 "ru": "Варианты обмотки 2 или 3 витка для надёжной фиксации"},
"Over 4,600 ties per charge (18.5V 5.0Ah battery)": {
 "ar": "أكثر من 4,600 ربطة لكل شحنة (بطارية 18.5V 5.0Ah)",
 "de": "Über 4.600 Bindungen pro Ladung (18,5V 5,0Ah Akku)",
 "es": "Más de 4.600 amarres por carga (batería 18.5V 5.0Ah)",
 "fr": "Plus de 4 600 ligatures par charge (batterie 18,5V 5,0Ah)",
 "ja": "満充電あたり4,600回以上の結束（18.5V 5.0Ahバッテリー）",
 "pt": "Mais de 4.600 amarres por carga (bateria 18.5V 5.0Ah)",
 "ru": "Более 4 600 вязок на заряд (аккумулятор 18,5V 5,0Ah)"},
"Ergonomic lightweight design — 2.65-2.7kg": {
 "ar": "تصميم خفيف مريح — 2.65-2.7kg",
 "de": "Ergonomisches leichtes Design — 2,65-2,7kg",
 "es": "Diseño ergonómico y ligero — 2,65-2,7kg",
 "fr": "Conception ergonomique et légère — 2,65-2,7kg",
 "ja": "人間工学に基づいた軽量設計 — 2.65-2.7kg",
 "pt": "Design ergonômico e leve — 2,65-2,7kg",
 "ru": "Эргономичный лёгкий дизайн — 2,65-2,7кг"},
"Upgraded high-power carbon brush motor": {
 "ar": "محرك فرش كربوني عالي القوة مطور",
 "de": "Verbesserter Hochleistungs-Kohlebürstenmotor",
 "es": "Motor de carbón de alta potencia mejorado",
 "fr": "Moteur à charbon haute puissance amélioré",
 "ja": "改良型高出力カーボンブラシモーター",
 "pt": "Motor de carbão de alta potência melhorado",
 "ru": "Улучшенный высокомощный коллекторный двигатель"},
"Bend rebar 4-36mm in 2-5 seconds": {
 "ar": "اثنِ حديد التسليح 4-36mm في 2-5 ثوانٍ",
 "de": "Bewehrung 4-36mm in 2-5 Sekunden biegen",
 "es": "Doblar armadura de 4-36mm en 2-5 segundos",
 "fr": "Courber l'armature 4-36mm en 2-5 secondes",
 "ja": "鉄筋を4〜36mmを2〜5秒で曲げる",
 "pt": "Dobrar armadura de 4-36mm em 2-5 segundos",
 "ru": "Гнуть арматуру 4-36mm за 2-5 секунд"},
"0-130° angle adjustment via die head": {
 "ar": "ضبط زاوية 0-130° عبر رأس القالب",
 "de": "0-130° Winkelverstellung über den Matrizenkopf",
 "es": "Ajuste de ángulo 0-130° mediante cabeza de dado",
 "fr": "Réglage d'angle 0-130° via la tête de matrice",
 "ja": "ダイスヘッドによる0〜130°角度調整",
 "pt": "Ajuste de ângulo 0-130° via cabeça da matriz",
 "ru": "Регулировка угла 0-130° через головку вкладыша"},
"High-strength 600# spherical molybdenum round steel": {
 "ar": "فولاذ كروي من الموليبدينوم عالي المتانة 600#",
 "de": "Hochfester 600# kugelförmiger Molybdän-Rundstahl",
 "es": "Acero redondo esférico de molibdeno de alta resistencia 600#",
 "fr": "Acier rond sphérique en molybdène haute résistance 600#",
 "ja": "高強度600#球状モリブデン丸鋼",
 "pt": "Aço redondo esférico de molibdênio de alta resistência 600#",
 "ru": "Высокопрочная сферическая молибденовая круглая сталь 600#"},
"Japanese imported knife shaft seal rings": {
 "ar": "حلقات seal لمحور السكين مستوردة من اليابان",
 "de": "Aus Japan importierte Messerwellen-Dichtungsringe",
 "es": "Anillos de sellado de eje de cuchilla importados de Japón",
 "fr": "Anneaux de joint d'arbre de couteau importés du Japon",
 "ja": "日本製輸入ナイフゼシャフトシールリング",
 "pt": "Anéis de vedação de eixo de faca importados do Japão",
 "ru": "Импортные из Японии уплотнительные кольца вала ножа"},
"#32 or #46 hydraulic oil compatible": {
 "ar": "متوافق مع زيت هيدروليكي #32 أو #46",
 "de": "#32 oder #46 Hydrauliköl kompatibel",
 "es": "Compatible con aceite hidráulico #32 o #46",
 "fr": "Compatible avec l'huile hydraulique #32 ou #46",
 "ja": "#32または#46の油圧オイルに対応",
 "pt": "Compatível com óleo hidráulico #32 ou #46",
 "ru": "Совместимо с гидравлическим маслом #32 или #46"},
"High-power brushless motor — 3200W": {
 "ar": "محرك بدون فرشاة عالي القوة — 3200W",
 "de": "Hochleistungs-Bürstenloser Motor — 3200W",
 "es": "Motor sin escobillas de alta potencia — 3200W",
 "fr": "Moteur sans balais haute puissance — 3200W",
 "ja": "高出力ブラシレスモーター — 3200W",
 "pt": "Motor sem escova de alta potência — 3200W",
 "ru": "Высокомощный бессчёточный двигатель — 3200W"},
"Bend rebar 10-28mm in 2-4 seconds": {
 "ar": "اثنِ حديد التسليح 10-28mm في 2-4 ثوانٍ",
 "de": "Bewehrung 10-28mm in 2-4 Sekunden biegen",
 "es": "Doblar armadura de 10-28mm en 2-4 segundos",
 "fr": "Courber l'armature 10-28mm en 2-4 secondes",
 "ja": "鉄筋を10〜28mmを2〜4秒で曲げる",
 "pt": "Dobrar armadura de 10-28mm em 2-4 segundos",
 "ru": "Гнуть арматуру 10-28mm за 2-4 секунды"},
"0-130° angle adjustment": {
 "ar": "ضبط زاوية 0-130°", "de": "0-130° Winkelverstellung", "es": "Ajuste de ángulo 0-130°",
 "fr": "Réglage d'angle 0-130°", "ja": "0〜130°角度調整", "pt": "Ajuste de ângulo 0-130°",
 "ru": "Регулировка угла 0-130°"},
"Longer operational life vs carbon brush motor": {
 "ar": "عمر تشغيلي أطول مقارنة بمحرك فرش الكربون",
 "de": "Längere Betriebslebensdauer als Kohlebürstenmotor",
 "es": "Mayor vida útil frente al motor de carbón",
 "fr": "Durée de vie opérationnelle plus longue qu'un moteur à charbon",
 "ja": "カーボンブラシモーターより長い稼働寿命",
 "pt": "Vida útil mais longa vs motor de carbão",
 "ru": "Больший срок службы по сравнению с коллекторным двигателем"},
"Automatic reset — portable, efficient and safe": {
 "ar": "إعادة ضبط تلقائية — محمول وفعال وآمن",
 "de": "Automatischer Reset — tragbar, effizient und sicher",
 "es": "Reinicio automático — portátil, eficiente y seguro",
 "fr": "Réinitialisation automatique — portable, efficace et sûr",
 "ja": "自動リセット — 携帯性・効率・安全性",
 "pt": "Redefinição automática — portátil, eficiente e seguro",
 "ru": "Автоматический сброс — портативный, эффективный и безопасный"},
"Cuts rebar, rod, bolts, chains and padlocks": {
 "ar": "يقطع حديد التسليح والقضبان والبراغي والسلاسل والأقفال",
 "de": "Schneidet Bewehrung, Stangen, Schrauben, Ketten und Vorhängeschlösser",
 "es": "Corta armadura, varillas, pernos, cadenas y candados",
 "fr": "Coupe l'armature, les barres, les boulons, les chaînes et les cadenas",
 "ja": "鉄筋・棒鋼・ボルト・チェーン・南京錠を切断",
 "pt": "Corta armadura, barras, parafusos, correntes e cadeados",
 "ru": "Режет арматуру, прутки, болты, цепи и навесные замки"},
"Spark-free cuts in 3-5 seconds": {
 "ar": "قطع خالٍ من الشرر في 3-5 ثوانٍ",
 "de": "Funkenfreie Schnitte in 3-5 Sekunden",
 "es": "Cortes sin chispas en 3-5 segundos",
 "fr": "Coupes sans étincelles en 3-5 secondes",
 "ja": "3〜5秒で火花なし切断",
 "pt": "Cortes sem faíscas em 3-5 segundos",
 "ru": "Резка без искр за 3-5 секунд"},
"Brushless motor — low vibration, low noise": {
 "ar": "محرك بدون فرشاة — اهتزاز منخفض، ضوضاء منخفضة",
 "de": "Bürstenloser Motor — geringe Vibration, geringer Lärm",
 "es": "Motor sin escobillas — baja vibración, bajo ruido",
 "fr": "Moteur sans balais — faible vibration, faible bruit",
 "ja": "ブラシレスモーター — 低振動・低騒音",
 "pt": "Motor sem escova — baixa vibração, baixo ruído",
 "ru": "Бессчёточный двигатель — низкая вибрация, низкий шум"},
"360° rotating head for tight spaces": {
 "ar": "رأس دوار 360° للأماكن الضيقة",
 "de": "360° drehbarer Kopf für enge Räume",
 "es": "Cabeza giratoria 360° para espacios estrechos",
 "fr": "Tête rotative 360° pour les espaces étroits",
 "ja": "狭い場所向け360°回転ヘッド",
 "pt": "Cabeça rotativa 360° para espaços estreitos",
 "ru": "Поворотная головка 360° для тесных мест"},
"Detachable handle for versatile use": {
 "ar": "مقبض قابل للفصل للاستخدام المتنوع",
 "de": "Abnehmbarer Griff für vielseitigen Einsatz",
 "es": "Mango desmontable para uso versátil",
 "fr": "Poignée amovible pour un usage polyvalent",
 "ja": "取り外し可能なハンドルで多彩な用途に対応",
 "pt": "Cabo destacável para uso versátil",
 "ru": "Съёмная рукоятка для универсального использования"},
"Smart controls with warning detection system": {
 "ar": "تحكم ذكي مع نظام كشف التحذيرات",
 "de": "Intelligente Steuerung mit Warnerkennungssystem",
 "es": "Controles inteligentes con sistema de detección de advertencia",
 "fr": "Commandes intelligentes avec système de détection d'alerte",
 "ja": "警告検知システム付きスマート制御",
 "pt": "Controles inteligentes com sistema de detecção de aviso",
 "ru": "Умное управление с системой обнаружения предупреждений"},
"Low spark — spark suppression reduces spatter by over 90%": {
 "ar": "شرر منخفض — كبح الشرر يقلل التناثر بأكثر من 90%",
 "de": "Wenig Funken — Funkenunterdrückung reduziert Spritzer um über 90 %",
 "es": "Bajo spark — la supresión de chispas reduce el salpicado en más del 90 %",
 "fr": "Faible étincelle — la suppression d'étincelles réduit les éclaboussures de plus de 90 %",
 "ja": "低火花 — 火花抑制で飛散を90%以上削減",
 "pt": "Baixo spark — a supressão de faíscas reduz o respingo em mais de 90 %",
 "ru": "Мало искр — подавление искр снижает разбрызгивание более чем на 90 %"},
"Effortless flush cuts up to 3mm from the surface": {
 "ar": "قطع متساوٍ سهل حتى 3mm من السطح",
 "de": "Mühelose bündige Schnitte bis 3mm unter der Oberfläche",
 "es": "Cortes al ras sin esfuerzo hasta 3mm de la superficie",
 "fr": "Coupes à ras faciles jusqu'à 3mm de la surface",
 "ja": "表面から3mmまでの楽な突き合わせ切断",
 "pt": "Cortes rasos sem esforço até 3mm da superfície",
 "ru": "Лёгкие заподлицо резы до 3mm от поверхности"},
"2.5 seconds to cut M10 rebar": {
 "ar": "2.5 ثانية لقطع حديد التسليح M10",
 "de": "2,5 Sekunden zum Schneiden von M10 Bewehrung",
 "es": "2,5 segundos para cortar armadura M10",
 "fr": "2,5 secondes pour couper l'armature M10",
 "ja": "M10鉄筋を2.5秒で切断",
 "pt": "2,5 segundos para cortar armadura M10",
 "ru": "2,5 секунды на резку арматуры M10"},
"Chip collection bag included": {
 "ar": "كيس جمع الرقائق مشمول", "de": "Spänesammeltasche enthalten", "es": "Bolsa de recolección de virutas incluida",
 "fr": "Sac de collecte de copeaux inclus", "ja": "チップ収集バッグ付属", "pt": "Bolsa de coleta de aparas incluída",
 "ru": "Мешок для сбора стружки в комплекте"},
"Brushless motor — low vibration, low noise, long lifespan": {
 "ar": "محرك بدون فرشاة — اهتزاز منخفض، ضوضاء منخفضة، عمر طويل",
 "de": "Bürstenloser Motor — geringe Vibration, geringer Lärm, lange Lebensdauer",
 "es": "Motor sin escobillas — baja vibración, bajo ruido, larga vida útil",
 "fr": "Moteur sans balais — faible vibration, faible bruit, longue durée de vie",
 "ja": "ブラシレスモーター — 低振動・低騒音・長寿命",
 "pt": "Motor sem escova — baixa vibração, baixo ruído, longa vida útil",
 "ru": "Бессчёточный двигатель — низкая вибрация, низкий шум, долгий срок службы"},
"3 position adjustable side handle": {
 "ar": "مقبض جانبي قابل للضبط بـ 3 أوضاع",
 "de": "3-Positionen verstellbarer Seitengriff",
 "es": "Mango lateral ajustable de 3 posiciones",
 "fr": "Poignée latérale réglable sur 3 positions",
 "ja": "3段階調整サイドハンドル",
 "pt": "Cabo lateral ajustável de 3 posições",
 "ru": "Боковая рукоятка с регулировкой в 3 положениях"},
"Used in construction, industry and rescue/emergency operations": {
 "ar": "تُستخدم في البناء والصناعة وعمليات الإنقاذ/الطوارئ",
 "de": "Eingesetzt im Bauwesen, in der Industrie und bei Rettungs-/Notfalleinsätzen",
 "es": "Usado en construcción, industria y operaciones de rescate/emergencia",
 "fr": "Utilisé dans la construction, l'industrie et les opérations de secours/urgence",
 "ja": "建設・産業・救急・緊急作業に使用",
 "pt": "Usado em construção, indústria e operações de resgate/emergência",
 "ru": "Применяется в строительстве, промышленности и спасательных/аварийных работах"},
"High-power carbon brush motor — strong cutting force": {
 "ar": "محرك فرش كربوني عالي القوة — قوة قطع قوية",
 "de": "Hochleistungs-Kohlebürstenmotor — starke Schnittkraft",
 "es": "Motor de carbón de alta potencia — fuerte fuerza de corte",
 "fr": "Moteur à charbon haute puissance — forte force de coupe",
 "ja": "高出力カーボンブラシモーター — 強力な切断力",
 "pt": "Motor de carbão de alta potência — forte força de corte",
 "ru": "Высокомощный коллекторный двигатель — сильная режущая сила"},
"Cut rebar in 2.5-4 seconds without sparks": {
 "ar": "اقطع حديد التسليح في 2.5-4 ثوانٍ دون شرر",
 "de": "Bewehrung in 2,5-4 Sekunden funkenfrei schneiden",
 "es": "Cortar armadura en 2,5-4 segundos sin chispas",
 "fr": "Couper l'armature en 2,5-4 secondes sans étincelles",
 "ja": "2.5〜4秒で火花なしに鉄筋を切断",
 "pt": "Cortar armadura em 2,5-4 segundos sem faíscas",
 "ru": "Резать арматуру за 2,5-4 секунды без искр"},
"High-strength iron alloy forged material — 600# ball-molybdenum": {
 "ar": "مادة م forged من سبيكة حديد عالية المتانة — موليبدينوم كروي 600#",
 "de": "Hochfester Eisenlegierungs-Schmiedematerial — 600# Kugelmolybdän",
 "es": "Material forjado de aleación de hierro de alta resistencia — molibdeno esférico 600#",
 "fr": "Matériau forgé en alliage de fer haute résistance — molybdène sphérique 600#",
 "ja": "高強度鉄合金鍛造材 — 600#球状モリブデン",
 "pt": "Material forjado de liga de ferro de alta resistência — molibdênio esférico 600#",
 "ru": "Кованый материал из высокопрочного железного сплава — сферический молибден 600#"},
"Patented triple-plunger hole design": {
 "ar": "تصميم ثقب مكبس ثلاثي ببراءة اختراع",
 "de": "Patentiertes Dreifach-Kolbenloch-Design",
 "es": "Diseño de orificio de triple émbolo patentado",
 "fr": "Conception de trou à triple plongeur brevetée",
 "ja": "特許取得済みトリプルプランジャー穴設計",
 "pt": "Design de furo de triplo êmbolo patenteado",
 "ru": "Запатентованная конструкция отверстия с тройным плунжером"},
"Japanese imported cutter shaft seals": {
 "ar": "ح seals لمحور القاطع مستوردة من اليابان",
 "de": "Aus Japan importierte Schneidwellen-Dichtungen",
 "es": "Sellos de eje de cortador importados de Japón",
 "fr": "Joint d'arbre de coupe importés du Japon",
 "ja": "日本製輸入カッターシャフトシール",
 "pt": "Vedação de eixo de cortador importada do Japão",
 "ru": "Импортные из Японии уплотнения вала резца"},
"Cordless portable design for on-site flexibility": {
 "ar": "تصميم محمول لاسلكي لمرونة في الموقع",
 "de": "Kabelloses tragbares Design für Flexibilität vor Ort",
 "es": "Diseño portátil inalámbrico para flexibilidad en obra",
 "fr": "Conception portable sans fil pour une flexibilité sur site",
 "ja": "現場での柔軟性のためのコードレス携帯設計",
 "pt": "Design portátil sem fio para flexibilidade no local",
 "ru": "Беспроводная портативная конструкция для гибкости на объекте"},
"Handles 16-32mm socket and 16-40mm rebar": {
 "ar": "يتعامل مع موصل 16-32mm وحديد تسليح 16-40mm",
 "de": "Bewältigt 16-32mm Sockel und 16-40mm Bewehrung",
 "es": "Maneja socket de 16-32mm y armadura de 16-40mm",
 "fr": "Gère douille 16-32mm et armature 16-40mm",
 "ja": "16-32mmソケットと16-40mm鉄筋に対応",
 "pt": "Lida com soquete de 16-32mm e armadura de 16-40mm",
 "ru": "Работает с гнездом 16-32mm и арматурой 16-40mm"},
"Max torque: 1200N": {
 "ar": "عزم الدوران الأقصى: 1200N", "de": "Max. Drehmoment: 1200N", "es": "Par máximo: 1200N",
 "fr": "Couple max. : 1200N", "ja": "最大トルク: 1200N", "pt": "Torque máx.: 1200N", "ru": "Макс. крутящий момент: 1200N"},
"Motor speed: 3000 r/min": {
 "ar": "سرعة المحرك: 3000 r/min", "de": "Motordrehzahl: 3000 r/min", "es": "Velocidad del motor: 3000 r/min",
 "fr": "Vitesse du moteur : 3000 r/min", "ja": "モーター速度: 3000 r/min", "pt": "Velocidade do motor: 3000 r/min",
 "ru": "Скорость двигателя: 3000 r/min"},
"60-90 min working time per charge": {
 "ar": "وقت عمل 60-90 دقيقة لكل شحنة", "de": "60-90 min Arbeitszeit pro Ladung",
 "es": "60-90 min de tiempo de trabajo por carga", "fr": "60-90 min de temps de travail par charge",
 "ja": "満充電あたり60〜90分の稼働時間", "pt": "60-90 min de tempo de trabalho por carga",
 "ru": "60-90 мин время работы на заряд"},
"Compact and lightweight at 8.5kg": {
 "ar": "مضغوط وخفيف بوزن 8.5kg", "de": "Kompakt und leicht bei 8,5kg",
 "es": "Compacto y ligero de 8,5kg", "fr": "Compact et léger de 8,5kg",
 "ja": "8.5kgのコンパクト軽量設計", "pt": "Compacto e leve com 8,5kg",
 "ru": "Компактный и лёгкий, 8,5кг"},
"Designed for RT series rebar tying machines": {
 "ar": "مصمم لماكينات ربط حديد التسليح سلسلة RT",
 "de": "Ausgelegt für Rebar-Bindemaschinen der RT-Serie",
 "es": "Diseñado para máquinas de amarre de armadura serie RT",
 "fr": "Conçu pour les machines de ligature d'armature série RT",
 "ja": "RTシリーズ鉄筋結束機用に設計",
 "pt": "Projetado para máquinas de amarração de armadura série RT",
 "ru": "Предназначен для машин для вязки арматуры серии RT"},
'0.8mm single wire (21 Ga) — 100m per coil': {
 "ar": 'سلك مفرد 0.8mm (21 Ga) — 100m لكل لفة',
 "de": '0,8mm Einzeldraht (21 Ga) — 100m pro Spule',
 "es": 'Alambre simple de 0,8mm (21 Ga) — 100m por bobina',
 "fr": 'Fil simple 0,8mm (21 Ga) — 100m par bobine',
 "ja": '0.8mm単線（21 Ga） — 1巻100m',
 "pt": 'Arame simples de 0,8mm (21 Ga) — 100m por rolo',
 "ru": 'Одиночная проволока 0,8mm (21 Ga) — 100m на катушку'},
"High tensile strength: 480-520 MPa": {
 "ar": "قوة شد عالية: 480-520 MPa", "de": "Hohe Zugfestigkeit: 480-520 MPa",
 "es": "Alta resistencia a la tracción: 480-520 MPa", "fr": "Résistance à la traction élevée : 480-520 MPa",
 "ja": "高引張強度: 480-520 MPa", "pt": "Alta resistência à tração: 480-520 MPa",
 "ru": "Высокая прочность на разрыв: 480-520 MPa"},
"Multiple options: Galvanized / Black annealed / PVC-coated / Stainless steel": {
 "ar": "خيارات متعددة: مجلفن / أسود مرنن / مطلی بـ PVC / فولاذ مقاوم للصدأ",
 "de": "Mehrere Optionen: Verzinkt / schwarz geglüht / PVC-beschichtet / Edelstahl",
 "es": "Múltiples opciones: Galvanizado / negro recocido / con recubrimiento PVC / acero inoxidable",
 "fr": "Plusieurs options : Galvanisé / noir recuit / revêtu PVC / acier inoxydable",
 "ja": "複数オプション: 亜鉛メッキ / 黒焼なまし / PVCコーティング / ステンレス鋼",
 "pt": "Várias opções: Galvanizado / preto recozido / revestido PVC / aço inoxidável",
 "ru": "Несколько вариантов: Оцинкованный / чёрный отожжённый / с PVC-покрытием / нержавеющая сталь"},
"Q195 material for consistent, reliable performance": {
 "ar": "مادة Q195 لأداء متسق وموثوق",
 "de": "Q195 Material für gleichbleibende, zuverlässige Leistung",
 "es": "Material Q195 para un rendimiento constante y fiable",
 "fr": "Matériau Q195 pour des performances constantes et fiables",
 "ja": "Q195材で安定した信頼できる性能",
 "pt": "Material Q195 para desempenho consistente e confiável",
 "ru": "Материал Q195 для стабильной надёжной работы"}
}

for k, v in PATCH.items():
    T[k] = v
json.dump(T, open(SRC / "_translations.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("patched B:", len(PATCH))
